Repository orppst/pst-gui, pull requests merged in 2023-11, with the labels that each got.

#29 fix to #23: PerformanceParameters of a TechnicalGoal now editable;
  src/main/webui/src/commonInputs/NumberInputPlusUnit.tsx
  src/main/webui/src/generated/proposalToolComponents.ts
  src/main/webui/src/observations/targetType.form.tsx
  src/main/webui/src/physicalUnits/PhysicalUnits.tsx
  src/main/webui/src/technicalGoals/Goals.tsx
  src/main/webui/src/technicalGoals/edit.group.tsx
  src/main/webui/src/technicalGoals/performance.form.tsx
  src/main/webui/src/technicalGoals/render.technicalGoal.tsx
  src/main/webui/src/technicalGoals/spectrum.form.tsx
  src/main/webui/src/technicalGoals/table.row.tsx
Labels: bug, enhancement

#32 Abs changes technical goal edit issue23
  src/main/webui/src/commonInputs/NumberInputPlusUnit.tsx
  src/main/webui/src/physicalUnits/PhysicalUnits.tsx
  src/main/webui/src/technicalGoals/edit.group.tsx
  src/main/webui/src/technicalGoals/performance.form.tsx
  src/main/webui/src/technicalGoals/render.technicalGoal.tsx
Labels: documentation, enhancement

#26 Upload a file when chosen, removing the second step #11
  src/main/webui/src/proposal/Documents.tsx
Labels: bug, enhancement

#27 resolves #1 (download proposal)
  .github/workflows/gradle.yml
  src/main/webui/package.json
  src/main/webui/src/proposal/Overview.tsx
  src/main/webui/src/proposal/Summary.tsx
  src/main/webui/src/proposal/downloadProposal.tsx
Labels: enhancement

#31 resolves #13 once done (edit and new observations show different things)
  src/main/webui/src/App2.tsx
  src/main/webui/src/observations/List.tsx
  src/main/webui/src/observations/edit.group.tsx
  src/main/webui/src/observations/edit.modal.tsx
  src/main/webui/src/observations/new.modal.tsx
  src/main/webui/src/observations/observationPanel.tsx
  src/main/webui/src/observations/observationTable.tsx
  src/main/webui/src/observations/targetType.form.tsx
  src/main/webui/src/observations/timingWindowGui.tsx
  src/main/webui/src/observations/timingWindows.form.tsx
  src/main/webui/yarn.lock
Labels: bug, enhancement

#36 resolves #14 by changing the realtive path to a root based path
  src/main/webui/src/App2.tsx
Labels: bug, enhancement

#43 docs missed
  src/main/webui/src/commonInputs/NumberInputPlusUnit.tsx
  src/main/webui/src/technicalGoals/edit.group.tsx
  src/main/webui/src/technicalGoals/edit.modal.tsx
  src/main/webui/src/technicalGoals/performance.form.tsx
  src/main/webui/src/technicalGoals/render.technicalGoal.tsx
  src/main/webui/src/technicalGoals/scienceSpectralWindowGui.tsx
  src/main/webui/src/technicalGoals/spectrum.form.tsx
  src/main/webui/src/technicalGoals/technicalGoalTable.tsx
  src/main/webui/src/technicalGoals/technicalGoalsPanel.tsx
Labels: documentation

#50 more docs
  src/main/webui/src/Investigators/List.tsx
  src/main/webui/src/Investigators/New.tsx
  src/main/webui/src/targets/List.tsx
  src/main/webui/src/targets/New.tsx
  src/main/webui/src/targets/RenderTarget.tsx
Labels: documentation

#54 tries to resolve #49
  src/main/webui/src/targets/New.tsx
Labels: UI enhancment

#68 resolves #57 (locking out observations till targets and technical goals exist)
  src/main/webui/src/commonButtons/buttonInterfaceProps.tsx
  src/main/webui/src/commonButtons/navigation.tsx
  src/main/webui/src/observations/observationPanel.tsx
Labels: bug, enhancement, UI enhancment

#39 loads of constants and attempted to fix layouts to 80 chars
  src/main/webui/src/App2.tsx
  src/main/webui/src/ColourSchemeToggle.tsx
  src/main/webui/src/Investigators/List.tsx
  src/main/webui/src/Investigators/New.tsx
  src/main/webui/src/commonButtons/accordianControls.tsx
  src/main/webui/src/commonButtons/add.tsx
  src/main/webui/src/commonButtons/clone.tsx
  src/main/webui/src/commonButtons/databaseSearch.tsx
  src/main/webui/src/commonButtons/delete.tsx
  src/main/webui/src/commonButtons/download.tsx
  src/main/webui/src/commonButtons/routeBack.tsx
  src/main/webui/src/commonButtons/save.tsx
  src/main/webui/src/commonButtons/upload.tsx
  src/main/webui/src/commonButtons/viewEdit.tsx
  src/main/webui/src/commonInputs/NumberInputPlusUnit.tsx
  src/main/webui/src/constants.tsx
  src/main/webui/src/observations/observationTable.tsx
  src/main/webui/src/observations/targetType.form.tsx
  src/main/webui/src/physicalUnits/PhysicalUnits.tsx
  src/main/webui/src/proposal/Documents.tsx
  src/main/webui/src/proposal/New.tsx
  src/main/webui/src/proposal/Overview.tsx
  src/main/webui/src/proposal/Summary.tsx
  src/main/webui/src/proposal/Title.tsx
  src/main/webui/src/proposal/downloadProposal.tsx
  src/main/webui/src/targets/List.tsx
  src/main/webui/src/targets/New.tsx
  src/main/webui/src/technicalGoals/edit.group.tsx
  src/main/webui/src/technicalGoals/performance.form.tsx
  src/main/webui/src/technicalGoals/render.technicalGoal.tsx
  src/main/webui/src/technicalGoals/spectrum.form.tsx
  src/main/webui/src/technicalGoals/technicalGoalsPanel.tsx
Labels: enhancement

#58 resolves #5 as discussed within recent zoom meeting
  src/main/webui/src/App2.tsx
Labels: UI enhancment

#61 add ability to store timing windows on creation of a new observation
  src/main/webui/src/observations/edit.group.tsx
  src/main/webui/src/observations/timingWindowApi.tsx
Labels: bug, inportant

#55 Resolves #51 add string limits to create proposal
  src/main/webui/src/commonInputs/remainingCharacterCount.tsx
  src/main/webui/src/proposal/New.tsx
  src/main/webui/src/proposal/Summary.tsx
  src/main/webui/src/proposal/Title.tsx
Labels: UI enhancment

#64 adds aladin to the target page.
  src/main/webui/src/App2.tsx
  src/main/webui/src/constants.tsx
  src/main/webui/src/targets/New.tsx
  src/main/webui/src/targets/aladin.css
  src/main/webui/src/targets/aladinHelperMethods.tsx
  src/main/webui/src/targets/aladinTypes.tsx
  src/main/webui/tsconfig.json
Labels: enhancement, UI enhancment
